### ISSUE TITLE
How to redirect from HTTP to HTTPS?

### ISSUE THREAD

**Issue by diavrank** [justsml/ssl-proxy#16]
Hi, when I try to enter to my web app through HTTP appears this:

![Screen Shot 2020-07-22 at 19 12 12](https://user-images.githubusercontent.com/39581375/88241365-855a6d00-cc4f-11ea-8fa0-c396ddb135ce.png)

How can I configure my docker-compose.yml to redirect HTTP to HTTPS?

My current docker-compose.yml is the following:

```
version: '3'

services:
  app:
    container_name: app
    depends_on:
      - mongo
    image: myapp-web
    restart: on-failure
    build:
      context: .
      dockerfile: dockerfile
    env_file: docker.env
    networks:
      - farefo-net
  ssl-proxy:
    container_name: ssl-proxy
    image: justsml/ssl-proxy:latest
    environment:
      - HTTPS_PORT=443
      - SERVER_NAME=myapp.com
      - UPSTREAM_TARGET=app:3000
      - CERT_PUBLIC_PATH=/certs/fullchain.pem
      - CERT_PRIVATE_PATH=/certs/privkey.pem
    volumes:
      - /certs:/certs:ro
    ports:
      - 443:443
      - 80:443
    networks:
      - farefo-net
  mongo:
    container_name: mongo
    command:
      - --storageEngine=wiredTiger
    image: mongo:4.2.5-bionic
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: username
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - $PWD/data:/data/db
      - $PWD/database:/opt/database
    networks:
      - farefo-net
networks:
  farefo-net:
```
