### ISSUE TITLE
Startup fails due to certbot sudo command usage

### ISSUE THREAD

**Issue by dhm116** [justsml/ssl-proxy#8]
When running the `compose up -d {service}` command to try this out for the first time, this is what I saw:
```bash
nginx_1     |  ********** STARTING NGINX HTTPS/AUTH PROXY **********
nginx_1     |
nginx_1     |
nginx_1     | /www/entrypoint.sh: line 21: sudo: command not found
```

Here is my dumbed-down compose file:
```yaml
version: "3"

services:

  nginx:
    image: justsml/ssl-proxy:latest
    ports:
      - "443:443"
    restart: unless-stopped
    volumes:
      - ./configs/nginx/certs:/certs
    environment:
      - HTTPS_PORT=443
      - SERVER_NAME=servicename.127.0.0.1.xip.io
      - UPSTREAM_TARGET=upstream.127.0.0.1.xip.io:4433
      - CERT_AUTO=true
      - CERT_PUBLIC_PATH=/certs/fullchain.pem
      - CERT_PRIVATE_PATH=/certs/privkey.pem
    depends_on:
      - servicename
```
It looks like perhaps `sudo` just needs to be removed from that script?
